version: '3'
services:
  web:
    build: ./web
    image: ridwan3030/first-repo-aws
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build: ./api
    image: ridwan3030/first-repo-aws
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
